services:
- type: web
  name: performance-insights-api
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  envVars:
    - key: CONTENTSTUDIO_API_KEY
      value: null  # Will be set in Render dashboard
    - key: DEEPSEEK_API_KEY
      value: null  # Will be set in Render dashboard
    - key: GOOGLE_ANALYTICS_API_KEY
      value: null  # Will be set in Render dashboard
    - key: REDDIT_CLIENT_ID
      value: null  # Will be set in Render dashboard
    - key: REDDIT_SECRET
      value: null  # Will be set in Render dashboard
    - key: PORT
      value: 10000
  disk:
    name: data
    mountPath: /app
